#!/bin/sh
# postinst script for mopidy-spotify

set -e

case "$1" in
    configure)
        chown mopidy:audio /var/cache/mopidy/spotify
        chown mopidy:audio /var/lib/mopidy/spotify
        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$'" >&2
        exit 1
        ;;

esac

#DEBHELPER#

exit 0
